// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/header/Header.vue')['default']
    Navigation: typeof import('./src/components/navigation/Navigation.vue')['default']
    NavigationList: typeof import('./src/components/navigation/NavigationList.vue')['default']
    Post: typeof import('./src/components/post/Post.vue')['default']
    SearchBar: typeof import('./src/components/search/SearchBar.vue')['default']
  }
}

export { }
